title: Krom ka guerrero
author: Topzzio
email: Menem@menem.com.eu
description: > # this means to ignore newlines until "baseurl:"
  I really like tacos and burritos

# social links
twitter_username: lmao # DO NOT include the @ character, or else the build will fail!
github_username:  lmao # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima